services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"     # MQTT
      - "9001:9001"     # WebSocket (опционально для HA)
    volumes:
      - ./data:/mqtt/data
      - ./config:/mqtt/config
    networks:
      - local-services-db_default
      - local-services-caddy_caddy

networks:
  local-services-db_default:
    external: true
  local-services-caddy_caddy:
    external: true
